<project xmlns="http://maven.apache.org/POM/4.0.0"><modelVersion>4.0.0</modelVersion>
<groupId>pq.a09</groupId><artifactId>ortam-deneme</artifactId><version>0</version><packaging>jar</packaging><dependencies>
<dependency><groupId>at.asitplus.signum</groupId><artifactId>indispensable-cosef-jvm</artifactId><version>3.26.0</version></dependency>
</dependencies></project>
